/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author Hctor
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        Panel = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        fndUsuario = new javax.swing.JLabel();
        lblContrasena = new javax.swing.JLabel();
        pwdContrasena = new javax.swing.JPasswordField();
        fndContrasena = new javax.swing.JLabel();
        btnSingIn = new javax.swing.JButton();
        fndSingIn = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de Sesión");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(400, 500));
        setMinimumSize(new java.awt.Dimension(400, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 500));
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Logo-Login.png"))); // NOI18N
        Panel.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(51, 51, 51));
        lblUsuario.setText("Usuario:");
        Panel.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        txtUsuario.setBackground(new java.awt.Color(220, 220, 220));
        txtUsuario.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(28, 28, 28));
        txtUsuario.setToolTipText("Escribe aquí tu nombre de usuario");
        txtUsuario.setBorder(null);
        txtUsuario.setOpaque(false);
        Panel.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 310, 30));

        fndUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/textLogin.png"))); // NOI18N
        Panel.add(fndUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        lblContrasena.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblContrasena.setForeground(new java.awt.Color(51, 51, 51));
        lblContrasena.setText("Contraseña:");
        Panel.add(lblContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        pwdContrasena.setBackground(new java.awt.Color(220, 220, 220));
        pwdContrasena.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        pwdContrasena.setForeground(new java.awt.Color(40, 40, 40));
        pwdContrasena.setToolTipText("Escribe aquí tu contraseña");
        pwdContrasena.setBorder(null);
        pwdContrasena.setOpaque(false);
        Panel.add(pwdContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 310, 30));

        fndContrasena.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        fndContrasena.setForeground(new java.awt.Color(40, 40, 40));
        fndContrasena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/textLogin.png"))); // NOI18N
        Panel.add(fndContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        btnSingIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/btnLogin.png"))); // NOI18N
        btnSingIn.setBorder(null);
        btnSingIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSingIn.setOpaque(false);
        btnSingIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSingInActionPerformed(evt);
            }
        });
        Panel.add(btnSingIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 130, 50));

        fndSingIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/btnLogin.png"))); // NOI18N
        Panel.add(fndSingIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, -1, -1));

        Fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/Login.png"))); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, Fondo, org.jdesktop.beansbinding.ELProperty.create("${background}"), Fondo, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        Panel.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSingInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSingInActionPerformed
        HomeADM homeA = new HomeADM();
        homeA.show();
        this.dispose();
    }//GEN-LAST:event_btnSingInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel Panel;
    private javax.swing.JButton btnSingIn;
    private javax.swing.JLabel fndContrasena;
    private javax.swing.JLabel fndSingIn;
    private javax.swing.JLabel fndUsuario;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField pwdContrasena;
    private javax.swing.JTextField txtUsuario;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
